# Deployments  Rolling Update
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30 
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      name: python-pod-app
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: lokey0426/hello-python-app:8
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
# Cluster IP  Service
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
  - port: 6000
    targetPort: 5000
